"""add quiz attempts and student answers

Revision ID: e53446217281
Revises: 18189ac62018
Create Date: 2026-08-12 08:04:05.607141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e53446217281'
down_revision: Union[str, Sequence[str], None] = '18189ac62018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Quiz_Attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['Papers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Quiz_Attempts_paper_id'), 'Quiz_Attempts', ['paper_id'], unique=False)
    op.create_index(op.f('ix_Quiz_Attempts_user_id'), 'Quiz_Attempts', ['user_id'], unique=False)
    op.create_table('Student_Answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option_id', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['Quiz_Attempts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['Questions.id'], ),
    sa.ForeignKeyConstraint(['selected_option_id'], ['Question_Options.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Student_Answers_attempt_id'), 'Student_Answers', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_Student_Answers_question_id'), 'Student_Answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_Student_Answers_user_id'), 'Student_Answers', ['user_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index(op.f('ix_Student_Answers_user_id'), table_name='Student_Answers')
    op.drop_index(op.f('ix_Student_Answers_question_id'), table_name='Student_Answers')
    op.drop_index(op.f('ix_Student_Answers_attempt_id'), table_name='Student_Answers')
    op.drop_table('Student_Answers')
    op.drop_index(op.f('ix_Quiz_Attempts_user_id'), table_name='Quiz_Attempts')
    op.drop_index(op.f('ix_Quiz_Attempts_paper_id'), table_name='Quiz_Attempts')
    op.drop_table('Quiz_Attempts')
    # ### end Alembic commands ###
